name: app-commit

on:
  workflow_dispatch:
    inputs:
      file:
        description: "Relative path to file to update"
        required: false
        default: ".github/healthcheck"
      content:
        description: "Line to append"
        required: false
        default: "updated by app at $GITHUB_RUN_ID"

permissions:
  contents: read

concurrency:
  group: app-commit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commit:
    runs-on: ubuntu-latest
    # environment: merge   # Optional: gate with a protected environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get GitHub App installation token
        id: app-token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f422b6d3795075f7a4c
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Configure git as App bot
        env:
          GH_APP_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config user.name "github-app[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_APP_TOKEN}@github.com/${{ github.repository }}.git

      - name: Make a change and push to main
        env:
          FILE: ${{ github.event.inputs.file }}
          CONTENT: ${{ github.event.inputs.content }}
        run: |
          echo "${CONTENT}" >> "${FILE}"
          git add "${FILE}"
          git commit -m "chore(app): automated update via GitHub App"
          git push origin HEAD:main