name: app-commit

on:
  workflow_dispatch:
    inputs:
      file:
        description: "Relative path to file to update"
        required: false
        default: ".github/healthcheck"
      content:
        description: "Line to append"
        required: false
        default: "updated by app at $GITHUB_RUN_ID"

permissions:
  contents: read  # job uses the App installation token for push

jobs:
  commit:
    name: Commit to main using GitHub App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Generate installation token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Configure git as App bot
        run: |
          git config user.name "github-app[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}.git

      - name: Make a change and push to main
        shell: bash
        run: |
          set -euo pipefail
          file_path="${{ github.event.inputs.file }}"
          line="${{ github.event.inputs.content }}"
          mkdir -p "$(dirname "$file_path")"
          echo "$line" >> "$file_path"
          git add "$file_path"
          git commit -m "chore(app): automated update via GitHub App"
          # Push directly to main (requires App to be allowed to bypass PR requirements in branch protection)
          git push origin HEAD:main