name: ci-smoke
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  smoke:
    name: smoke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Basic repo sanity
        run: |
          echo "Repo root:"
          ls -la
          test -f "OutlookMailSorter.sln"
          test -f "OutlookMailSorter.csproj"

      - name: Tooling info
        run: |
          dotnet --info || true
          echo "Smoke check OK"
